"""Provider Adapter domain models and execution contracts."""

from datetime import datetime, timezone
from typing import Any, Dict, List, Optional
from pydantic import Field

from infuse.contracts.common import InfuseBaseModel
from infuse.version import SCHEMA_VERSION


def _utc_now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


class ProviderUsage(InfuseBaseModel):
    """Normalized token usage metadata reported by a provider."""
    input_tokens: int = Field(default=0, ge=0, description="Tokens consumed by prompt input.")
    output_tokens: int = Field(default=0, ge=0, description="Tokens generated by model completion.")
    total_tokens: int = Field(default=0, ge=0, description="Total tokens consumed.")
    cached_tokens: int = Field(default=0, ge=0, description="Prompt tokens read from prefix cache.")
    is_authoritative: bool = Field(
        default=True,
        description="True if extracted directly from provider response; False if estimated."
    )
    details: Dict[str, Any] = Field(
        default_factory=dict,
        description="Provider-specific breakdown (e.g. reasoning tokens, cache creation tokens)."
    )


class ProviderErrorRecord(InfuseBaseModel):
    """Normalized error representation for provider-level failures."""
    provider_id: str = Field(..., description="Provider identifier.")
    model_id: Optional[str] = Field(default=None, description="Model identifier if known.")
    error_type: str = Field(default="PROVIDER_ERROR", description="Categorical error category.")
    error_code: Optional[str] = Field(default=None, description="Provider-specific error code string.")
    message: str = Field(..., description="Human-readable normalized error message.")
    is_retryable: bool = Field(default=False, description="Whether this error is transient and retryable.")
    http_status: Optional[int] = Field(default=None, description="HTTP status code if applicable.")
    provider_request_id: Optional[str] = Field(default=None, description="Provider request ID if returned.")
    raw_error: Optional[Dict[str, Any]] = Field(default=None, description="Raw provider error object.")
    timestamp: str = Field(default_factory=_utc_now_iso, description="UTC ISO timestamp.")


class ProviderExecutionRequest(InfuseBaseModel):
    """Universal execution request sent to a Provider Adapter."""
    execution_id: str = Field(..., description="Unique execution identity.")
    request_id: str = Field(..., description="Originating request identity.")
    task_id: str = Field(..., description="Task context identity.")
    provider_id: str = Field(..., description="Target provider identifier.")
    model_id: str = Field(..., description="Target model identifier.")
    messages: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Normalized conversation messages."
    )
    tools: Optional[List[Dict[str, Any]]] = Field(
        default=None,
        description="Normalized tool / function calling schemas."
    )
    parameters: Dict[str, Any] = Field(
        default_factory=dict,
        description="Hyperparameters (temperature, max_tokens, etc.)."
    )
    raw_payload: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Optional caller raw payload for lossless pass-through."
    )
    stream: bool = Field(
        default=False,
        description="Whether streaming chunk delivery is requested."
    )
    metadata: Dict[str, Any] = Field(
        default_factory=dict,
        description="Contextual metadata for execution."
    )
    schema_version: str = Field(
        default=SCHEMA_VERSION,
        description="Schema contract version."
    )


class ProviderExecutionResponse(InfuseBaseModel):
    """Normalized execution response produced by a Provider Adapter."""
    execution_id: str = Field(..., description="Unique execution identity.")
    request_id: str = Field(..., description="Originating request identity.")
    provider_id: str = Field(..., description="Executing provider identifier.")
    model_id: str = Field(..., description="Executing model identifier.")
    content: Optional[str] = Field(default=None, description="Generated completion text content.")
    role: str = Field(default="assistant", description="Message role.")
    tool_calls: Optional[List[Dict[str, Any]]] = Field(
        default=None,
        description="Tool invocations requested by the model."
    )
    finish_reason: Optional[str] = Field(
        default="stop",
        description="Termination reason (e.g. stop, length, tool_calls)."
    )
    usage: ProviderUsage = Field(
        default_factory=ProviderUsage,
        description="Normalized token usage measurements."
    )
    latency_ms: float = Field(
        default=0.0,
        ge=0.0,
        description="Round-trip provider invocation duration in milliseconds."
    )
    provider_request_id: Optional[str] = Field(
        default=None,
        description="Provider-assigned request / trace identifier."
    )
    raw_response: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Raw provider response payload for lossless audit."
    )
    metadata: Dict[str, Any] = Field(
        default_factory=dict,
        description="Provider-specific execution metadata."
    )
    schema_version: str = Field(
        default=SCHEMA_VERSION,
        description="Schema contract version."
    )


class ProviderExecutionChunk(InfuseBaseModel):
    """Normalized streaming delta chunk emitted during provider streaming execution."""
    execution_id: str = Field(..., description="Execution identity.")
    provider_id: str = Field(..., description="Provider identifier.")
    model_id: str = Field(..., description="Model identifier.")
    delta_content: Optional[str] = Field(default=None, description="Incremental text chunk.")
    delta_tool_calls: Optional[List[Dict[str, Any]]] = Field(
        default=None,
        description="Incremental tool calling fragments."
    )
    finish_reason: Optional[str] = Field(default=None, description="Termination reason if final chunk.")
    usage: Optional[ProviderUsage] = Field(
        default=None,
        description="Interim or final usage information if provided by the stream."
    )
    index: int = Field(default=0, ge=0, description="Chunk sequence index.")
    provider_request_id: Optional[str] = Field(default=None, description="Provider request identifier.")
